name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://aloysiussundar.github.io/gitforked/feed.xml"
