name: Latest Blog Posts
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily (or set to '0 * * * *' for hourly)
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull RSS Feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://aloysiussundar.github.io/gitforked/rss.xml"
          max_post_count: 5
